### ISSUE TITLE
Fingerprinter does not enter learning mode

### ISSUE THREAD

**Issue by smotomike** [bkbilly/mqtt_fingerprint_pi#5]
The fingerprint does not switch to enroll mode. When I publish via MQTT via Homeassistant or IOBrocker, the fingerprint does not respond at all for a few seconds and remains in scan mode.

Can I also put the fingerprint into learn mode via the console to rule out an error in MQTT?

When scanning the finger comes {"id": -1, "name": "unauthorized", "action": "unauthorized", "time": 1730058491, "confidence": 0}

So that should be fine.

**Comment by AxelHoss** [comment]
Did you find a solution? Im on the same issue. Never used this method for learning a finger

**Comment by bkbilly** [comment]
This only supports MQTT....
I've created some Scripts on Home Assistant that can help sending the correct MQTT topic. You can try them to check if it works for you.


## Fingerprint Enroll:
```yaml
alias: Fingerprint Up Enroll
sequence:
  - data:
      topic: fingerprint/set/mode/enroll
      payload_template: "{{ finger_id }}"
    action: mqtt.publish
mode: single
icon: mdi:fingerprint
fields:
  finger_id:
    selector:
      number:
        min: -1
        max: 100
    required: true
    default: -1
    name: Finger ID
    description: Finger ID
```

## Fingerprint Rename:
```yaml
alias: Fingerprint Up Rename
sequence:
  - metadata: {}
    data:
      qos: 0
      retain: false
      topic: fingerprint/set/mode/name_{{ finger_id }}
      payload: "{{ name }}"
    action: mqtt.publish
fields:
  finger_id:
    selector:
      number:
        min: -1
        max: 100
        step: 1
    name: Finger ID
    description: Finger ID
    required: true
  name:
    selector:
      text: null
    name: Name
    description: Person Name
    required: true
mode: single
icon: mdi:ornament
```

## Fingerprint Delete:
```yaml
alias: Fingerprint Up Delete
sequence:
  - metadata: {}
    data:
      qos: 0
      retain: false
      topic: fingerprint/set/mode/delete
      payload: "{{ finger_id }}"
    action: mqtt.publish
fields:
  finger_id:
    selector:
      number:
        min: 0
        max: 100
        step: 1
    name: Finger ID
    description: Finger ID
    required: true
mode: single
icon: mdi:fingerprint-off
```
