### ISSUE TITLE
List of fingerprints name in HA.

### ISSUE THREAD

**Issue by khseal** [bkbilly/mqtt_fingerprint_pi#7]
Is there any way to display a list of fingerprints in the Home Assist interface?

**Comment by bkbilly** [comment]
There is a way to do so, but it is not so elegant.

When the service starts or you delete/enroll a finger, it sends an MQTT message with the contents of the `devices.yaml` file in a json format under the topic `fingerprint/templates`.

You could create a new mqtt sensor that subscribes to this topic and shows the json.

**Comment by khseal** [comment]
Ok, thanks, useful information.

**Comment by khseal** [comment]
I don't understand how to make one sensor as a list.

**Comment by bkbilly** [comment]
I tried it out and it seems it a bit more difficult than I expected.
Finally I got it working by creating the sensor like so:
```yaml
mqtt:
  sensor:
    - name: "Fingerprint List"
      unique_id: "fingerprint_list"
      state_topic: "fingerprint/templates"
      value_template: >-
        {% set data = namespace(list=[]) %}
        {% for item in value_json %}
            {% set data.list = data.list + [item.id | string + ":" + item.name] %}
        {% endfor %}
        {{ data.list | join(", ") }}
```
